//
//  Breeds.swift
//  catsPOCSwft
//
//  Created by Claudia Cortes on 6/15/22.
//
// Generated by https://quicktype.io

import Foundation
import Alamofire
typealias Breeds = [Breed]
struct API {
    private static var  key = "c1f2e222-32ab-4581-89e7-953017a7e047";
    static var headers: HTTPHeaders = ["x-api-key": key]
}

struct Breed :Decodable{
    let adaptability, affectionLevel: Int?
    let altNames: String?
    let cfaURL: String?
    let childFriendly: Int?
    let countryCode, countryCodes, description: String?
    let dogFriendly, energyLevel, experimental, grooming: Int?
    let hairless, healthIssues, hypoallergenic: Int?
    let id: String
    let image: Image?
    let indoor, intelligence: Int?
    let lap: Int?
    let lifeSpan: String?
    let name: String
    let natural: Int?
    let origin: String?
    let rare: Int?
    let referenceImageID: String?
    let rex, sheddingLevel, shortLegs, socialNeeds: Int?
    let strangerFriendly, suppressedTail: Int?
    let temperament: String?
    let vcahospitalsURL: String?
    let vetstreetURL: String?
    let vocalisation: Int?
    let weight: Weight?
    let wikipediaURL: String?
    let bidability, catFriendly: Int?
}

struct Image:Decodable {
    let height: Int?
    let id: String?
    let url: String?
    let width: Int?
}

struct Weight:Decodable {
    let imperial, metric: String
}
